### ISSUE TITLE
Support relative includes

### ISSUE THREAD

**Issue by pyhedgehog** [AlexanderGrooff/nginx-static-analysis#25]
For example I have in nginx.conf line `include mime.types;`.
Then with full path:
```console
$ nginx-static-analysis --file /etc/nginx/nginx.conf
Traceback (most recent call last):
  File "/home/<USER>/.local/bin/nginx-static-analysis", line 8, in <module>
    sys.exit(main())
  File "/home/<USER>/.local/pipx/venvs/nginx-static-analysis/lib/python3.10/site-packages/nginx_analysis/main.py", line 21, in main
    root_config = parse_config(args.file)
  File "/home/<USER>/.local/pipx/venvs/nginx-static-analysis/lib/python3.10/site-packages/nginx_analysis/analysis.py", line 70, in parse_config
    set_parents_of_blocks(root_config, line_config)
  File "/home/<USER>/.local/pipx/venvs/nginx-static-analysis/lib/python3.10/site-packages/nginx_analysis/analysis.py", line 55, in set_parents_of_blocks
    set_parents_of_blocks(root_config, block_config)
  File "/home/<USER>/.local/pipx/venvs/nginx-static-analysis/lib/python3.10/site-packages/nginx_analysis/analysis.py", line 56, in set_parents_of_blocks
    set_parents_in_include(root_config, line_config)
  File "/home/<USER>/.local/pipx/venvs/nginx-static-analysis/lib/python3.10/site-packages/nginx_analysis/analysis.py", line 41, in set_parents_in_include
    nested_file_configs = root_config.get_files(nginx_to_regex(file_path))
  File "/home/<USER>/.local/pipx/venvs/nginx-static-analysis/lib/python3.10/site-packages/nginx_analysis/dataclasses.py", line 183, in get_files
    raise IndexError(f"{file_path_regex} not found in config")
IndexError: mime.types not found in config
```
But if I start it with relative parameter it works: `(cd /etc/nginx;nginx-static-analysis --file nginx.conf)`.
I think relative paths should be parsed against path of root config.

**Comment by AlexanderGrooff** [comment]
Hi there,

Thanks for catching this, you make a good point. I didn't consider relative paths yet, and it seems that Nginx defaults to prefixing relative paths with `/etc/nginx` (if [this SO](https://stackoverflow.com/a/25486871) is still valid). This should either:
1. Prefix relative paths with `/etc/nginx`
2. Use the dir in which the root config file is located

I'll see if I can fix this some time in the future, seems straightforward enough.

**Comment by pyhedgehog** [comment]
I've checked, it's relative to root config:
https://github.com/nginx/nginx/blob/489e1e61912a808fdaffb4f513426cb285f267a3/src/core/ngx_conf_file.c#L887

**Comment by AlexanderGrooff** [comment]
Thanks for the report. Should be fixed and tested in the latest release https://github.com/AlexanderGrooff/nginx-static-analysis/releases/tag/0.3.0
